<div class="pager">
<?php if ($back): ?>
	<a href="<?php echo str_replace('__PAGE__', ($page-1), $href) ?>">&laquo;&nbsp;Back</a>
<?php else: ?>
	&laquo;&nbsp;Back
<?php endif ?>

<?php if ($pages < 13): /* « Previous  1 2 3 4 5 6 7 8 9 10 11 12  Next » */ ?>

	<?php for ($i = 1; $i <= $pages; $i++): ?>
		<?php if ($i == $page+1): ?>
			<strong><?php echo $i ?></strong>
		<?php else: ?>
			<a href="<?php echo str_replace('__PAGE__', $i-1, $href) ?>"><?php echo $i ?></a>
		<?php endif ?>
	<?php endfor ?>

<?php elseif ($page < 9): /* « Previous  1 2 3 4 5 6 7 8 9 10 … 25 26  Next » */ ?>

	<?php for ($i = 1; $i <= 10; $i++): ?>
		<?php if ($i == $page+1): ?>
			<strong><?php echo $i ?></strong>
		<?php else: ?>
			<a href="<?php echo str_replace('__PAGE__', $i-1, $href) ?>"><?php echo $i ?></a>
		<?php endif ?>
	<?php endfor ?>
	&hellip;
	<a href="<?php echo str_replace('__PAGE__', $pages - 2, $href) ?>"><?php echo $pages - 1 ?></a>
	<a href="<?php echo str_replace('__PAGE__', $pages - 1, $href) ?>"><?php echo $pages ?></a>

<?php elseif ($page > $pages - 8): /* « Previous  1 2 … 17 18 19 20 21 22 23 24 25 26  Next » */ ?>
	<a href="<?php echo str_replace('__PAGE__', 0, $href) ?>">1</a>
	<a href="<?php echo str_replace('__PAGE__', 1, $href) ?>">2</a>
	&hellip;
	<?php for ($i = $pages - 9; $i <= $pages; $i++): ?>
		<?php if ($i == $page+1): ?>
			<strong><?php echo $i ?></strong>
		<?php else: ?>
			<a href="<?php echo str_replace('__PAGE__', $i-1, $href) ?>"><?php echo $i ?></a>
		<?php endif ?>
	<?php endfor ?>
<?php else: /* « Previous  1 2 … 5 6 7 8 9 10 11 12 13 14 … 25 26  Next » */ ?>
	<a href="<?php echo str_replace('__PAGE__', 0, $href) ?>">1</a>
	<a href="<?php echo str_replace('__PAGE__', 1, $href) ?>">2</a>
	&hellip;
	<?php for ($i = $page - 5; $i <= $page + 5; $i++): ?>
		<?php if ($i == $page+1): ?>
			<strong><?php echo $i ?></strong>
		<?php else: ?>
			<a href="<?php echo str_replace('__PAGE__', $i-1, $href) ?>"><?php echo $i ?></a>
		<?php endif ?>
	<?php endfor ?>
	&hellip;
	<a href="<?php echo str_replace('__PAGE__', $pages - 2, $href) ?>"><?php echo $pages - 1 ?></a>
	<a href="<?php echo str_replace('__PAGE__', $pages - 1, $href) ?>"><?php echo $pages ?></a>
<?php endif ?>

<?php if ($next): ?>
	<a href="<?php echo str_replace('__PAGE__', ($page+1), $href) ?>">Next&nbsp;&raquo;</a>
<?php else: ?>
	Next&nbsp;&raquo;
<?php endif ?>
</div>
