<div class="pager">
<?
if($back==true):
	echo '<a href="'.str_replace('__PAGE__',($page-1),$href).'">« Back</a> ';
else:
	echo '« Back ';
endif;
?>

<?php if ($page > 3): ?>
	<a href="<?php echo str_replace('__PAGE__', 0, $href) ?>">1</a>
	<?php if ($page != 4) echo '&hellip;' ?>
<?php endif ?>

<?php for ($i = $page - 2, $stop = $page + 3; $i < $stop; ++$i): ?>
	<?php if ($i < 1 OR $i > $pages) continue ?>
	<?php if ($page+1 == $i): ?>
		<strong><?php echo $i ?></strong>
	<?php else: ?>
		<a href="<?php echo str_replace('__PAGE__', $i-1, $href) ?>"><?php echo $i; ?></a>
	<?php endif ?>
<?php endfor ?>

<?php if ($page <= $pages - 3): ?>
	<?php if ($page != $pages - 3) echo '&hellip;' ?>
	<a href="<?php echo str_replace('__PAGE__', $pages-1, $href) ?>"><?php echo $pages ?></a>
<?php endif ?>
	
<?php
if($next==true):
	echo ' <a href="'.str_replace('__PAGE__',($page+1),$href).'">Next »</a>';
else:
	echo ' Next »';
endif;
?>
</div>
