<!DOCTYPE html>
<head>
	<meta charset="utf-8" />
	<meta http-equiv="refresh" content="3;url=<?php echo $url; ?>">

	<title>Redirect</title>

	<style type="text/css">
	body{
		margin-top:120px;
		padding:0px;
		background-color:#f0f0f0;
		letter-spacing:1px;
	}

	h1{
		background-color:#92CD00;
		margin:0px;
		font-size:18px;
		padding: 10px 25px;
		border-bottom: 3px solid #669900
	}
	
	#box{width:600px; margin:0px auto; border: 1px solid #669900; background:white}
	
	#info_box { padding:1em 2em; }
	
	</style>

</head>
<body>
	<div id='box'>
	<h1>Redirect</h1>
	<div id='info_box'>		
				
	Redirect to: <a href="<?php echo $url; ?>"><?php echo $url; ?></a>

		
	</div>
	
	</div>

</body>
</html>


