<ul class="pager">
<?php
if($back==true){
	echo '<li class="previous"><a href="'.str_replace('__PAGE__',($page-1),$href).'">&larr; Older</a></li>';
}else{
	echo '<li class="previous disabled"><a href="#">&larr; Older</a></li>';
}


if($next==true){
	echo '<li class="next"><a href="'.str_replace('__PAGE__',($page+1),$href).'">Newer &rarr;</a></li>';
}else{
	echo '<li class="next disabled"><a href="#">Newer &rarr;</a></li>';
}
?>
</ul>
