<ul class="pagination">
<?
if($back==true):
	echo '<li><a href="'.str_replace('__PAGE__',($page-1),$href).'">« Back</a></li> ';
else:
	echo '<li class="disabled"><a href="#">« Back</a></li>';
endif;
?>

<?php if ($page > 3): ?>
	<li><a href="<?php echo str_replace('__PAGE__', 0, $href) ?>">1</a></li>
	<?php if ($page != 4) echo '<li class="disabled"><a href="#">&hellip;</a><li/>' ?>
<?php endif ?>

<?php for ($i = $page - 2, $stop = $page + 3; $i < $stop; ++$i): ?>
	<?php if ($i < 1 OR $i > $pages) continue ?>
	<?php if ($page+1 == $i): ?>
		<li class="disabled"><a href="#"><?php echo $i ?></a></li>
	<?php else: ?>
		<li><a href="<?php echo str_replace('__PAGE__', $i-1, $href) ?>"><?php echo $i; ?></a></li>
	<?php endif ?>
<?php endfor ?>

<?php if ($page <= $pages - 3): ?>
	<?php if ($page != $pages - 3) echo '<li class="disabled"><a href="#">&hellip;</a></li>' ?>
	<li><a href="<?php echo str_replace('__PAGE__', $pages-1, $href) ?>"><?php echo $pages ?></a></li>
<?php endif ?>
	
<?php
if($next==true):
	echo ' <li><a href="'.str_replace('__PAGE__',($page+1),$href).'">Next »</a></li>';
else:
	echo '<li class="disabled"><a href="#">Next »</a></li>';
endif;
?>
</ul>
