<div class="pagination">
<?php
if($back==true){
	echo '<li><a href="'.str_replace('__PAGE__',($page-1),$href).'">« Back</a></li>';
}else{
	echo '<li class="disabled"><a href="#">« Back</li>';
}

echo '<li class="disabled"><a href="#">'.($page+1).' / '.$pages.'</a></li>';

if($next==true){
	echo '<li><a href="'.str_replace('__PAGE__',($page+1),$href).'">Next »</a></li>';
}else{
	echo '<li class="disabled"><a href="#">Next »</li>';
}
?>
</div>
