<?php defined('SPAWNM') OR die('No direct access allowed.'); ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="title" content="Spawn Framework - Open-Source php Framework" />
  	<meta name="Keywords" content="php framework, spawn, php5 framework, framework, mvc, MVC , spawnframework, spawn framework,  php, php5" />
  	<meta name="description" content="Spawn Framework - Open-Source php Framework" />
  	<meta name="Author" content="Paweł Makowski" />
	<title>Spawn Framework</title>

	<style type="text/css">
	body{
		margin-top:120px;
		padding:0px;
		background-color:#f0f0f0;
		letter-spacing:1px;
		text-align:center
	}

	h1{
		background-color:#92CD00;
		margin:0px;
		font-size:18px;
		padding: 10px 25px;
		border-bottom: 3px solid #669900;
		color: white
	}
	
	a{
		color: blue;
		text-decoration: none;
	}
	
	#box{
		width:400px; 
		margin:0px auto; 
		border: 1px solid #669900; 
		background:white
	}
	
	#info_box { 
		padding:1em 2em; 
	}
	
	#menu{
		font-size:12px;
		margin:0px;
		padding-top:20px
	}	
	</style>

</head>
<body>
	<div id='box'>
	<h1>Spawn Framework <?php echo SPAWNM; ?></h1>
	<div id='info_box'>		
				
	Hello World :)
	
	<p id='menu'>		
		<a href='http://spawnframework.com/tutorial'>Tutorial</a> | 
		<a href='http://spawnframework.com/documentation'>Documentation</a> | 		
		<a href='http://spawnframework.com/license'>License</a> |
		<a href='http://spawnframework.com/contact'>Contact</a>
	</p>		
	</div>
	
	</div>

</body>
</html>
